# Generated by Django 3.2 on 2021-04-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210427_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localarticle',
            name='location',
        ),
    ]
