# Generated by Django 3.2 on 2021-04-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210427_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schoolarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
