# Generated by Django 3.2 on 2021-04-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210423_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'Male'), ('E', 'ETC')], max_length=1),
        ),
    ]
